version: "3.3"

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    network_mode: bridge
    expose:
      - 6379
  
  api:
    build: .
    container_name: api
    restart: always
    network_mode: bridge
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - redis